#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <ctype.h>

int main()
{
    int opcao, validador_primeira_entrada, validar_num1, validar_num2;
    float num1, num2, soma, multiplicacao, divisao, subtracao;
    char limpa_buffer;

    printf(" Algoritmo feito pelo Aluno Ricardo Mauricio Demartini Barbosa\n Curso em análise e desenvolvimento de sistemas \n Número de Mátricula: 202222260\n Universidade LaSalle\n");

    /*Menu de opçoes*/
    do
    {
        printf("\nDigite 1 para Adição, 2 Subtração, 3 Divisão, 4 Multiplicação, 5 Potencia, 6 Raiz quadrada\n ");

        /*Validador vai receber a função scanf dentro dela pois a mesma fará uma comparação se o item digitado é um número e então retornará falso(0)*/

        validador_primeira_entrada = scanf("%d", &opcao); /*%d sendo do tipo inteiro, caso eu digitar um caracter, é retornado 0. pois %d com %c == False*/

        /*Nessa parte utilizei uma váriavel em char chamada limpa buffer dentro de um DO WHILE para capturar o último caractere digitado para não haver um loop no código*/
        do
        {
            limpa_buffer = getchar(); /*pegará a último caracter digitado sendo a tecla ENTER  que equivale a (/n)*/
        } while (limpa_buffer != '\n'); /*Limpando o buffer evitando o loop*/

        /*Aviso de alerta pedindo o valor novamente*/
        if (opcao < 1 || opcao > 6 || validador_primeira_entrada == 0)
        {
            validador_primeira_entrada = 0; /*Validação para caso a opção digitada for diferente de 1 a 6. Caso seja diferente, é retornado 0*/
            printf("Opçao invalida, digite novamente!");
        }
    } while (validador_primeira_entrada == 0); /*Caso seja 1 o laço é encerrado*/
    {
    }

    /*Entrada dos valores*/
    do
    {
        printf("Digite um número: ");
        validar_num1 = scanf("%f", &num1); /*Validador da variavel num1*

         /*Caso a opção seja subtração, adicão, multiplicação e divisão será pedido o segundo número*/
        if (opcao > 0 && opcao < 5)
        {
            printf("Digite o segundo número: ");
            validar_num2 = scanf("%f", &num2); /*Validador da variavel num2*/
        }

        /*nessa parte foi exatamente a mesmo esquema que foi feito acima, só que dessa vez usando validadores individuais*/
        do
        {
            limpa_buffer = getchar();  /*Reaproveitei a váriavel*/
        } while (limpa_buffer != '\n');

        /*Aviso de erro caso num1 ou num2 não sejam números*/

        if (validar_num1 == 0 || validar_num2 == 0)
        {
            printf("\nOpção inválida!Digite novamente!\n");
        }
    } while (validar_num1 == 0 || validar_num2 == 0);
    {
    }

    /*Cálculo das expressões aritméticas*/

    /* Adição*/
    if (opcao == 1)
    {
        soma = num1 + num2;
        printf("A soma dos números %f e %f é igual a: %f", num1, num2, soma);
    }
    /*Subtração*/
    if (opcao == 2)
    {
        while (num1 < num2)/*Em subtração foi feito uma validação*/
        {
            printf("O primeiro número não pode ser menor do que o segundo!Pois retornará negativo! Digite novamente!");
            printf("\nPrimeiro número");
            scanf("%f", &num1);
            printf("Segundo número");
            scanf("%f", &num2);
        }
        subtracao = num1 - num2;
        printf("A subtração entre os números %f e %f é igual a : %f", num1, num2, subtracao);
    }

    /*Divisão*/
    if (opcao == 3)
    {
        while (num1 == 0 || num2 == 0)/*Em divisão foi feito outra validação para o usuário não digitar 0*/
        {
            printf("O Divisor e nem o divendendo podem ser 0! Digite novamente!");
            printf("\nPrimeiro número (Dividendo)");
            scanf("%f", &num1);
            printf("Segundo número (Divisor)");
            scanf("%f", &num2);
        }
        divisao = num1 / num2;
        printf("A divisão dos números %f e %f é igual a: %f", num1, num2, divisao);
    }

    /*Multiplicação*/
    if (opcao == 4)
    {
        multiplicacao = num1 * num2;
        printf("A multiplicação dos números %f e %f é igual a: %f", num1, num2, multiplicacao);
    }
    /*Foram utlizadas funções para fazer o cálculo de potência e raiz quadrada*/

    /*Cálculo de Potência(Função)*/
    if (opcao == 5)
    {
        printf("O valor em potência do número %f é igual a %f", num1, pow(num1, 2));
    }

    /*Raiz(Função)*/
    if (opcao == 6)
    {
        printf("O valor da raiz quadrada de %f é igual a %f ", num1, sqrt(num1));
    }
    return 0;
}
